# Color Scheme
theme = "geohot"

[editor]
line-number = "absolute"
mouse = true
true-color = true
auto-save = true
bufferline = "always"
clipboard-provider = "pasteboard"
color-modes = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "underline"

[editor.indent-guides]
render = false
character = "│"

[editor.lsp]
display-inlay-hints = false
snippets = true

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "disable"

# Keybindings
[keys.normal]
# Add quick save/quit without overwriting the native Space leader menu
"space"."w" = ":write"
"space"."q" = ":quit"

# Buffer Management
"g" = { "]" = ":buffer-next", "[" = ":buffer-previous" }
"A-=" = ":write-all"

# Function Navigation
"tab" = "goto_next_function"
"S-tab" = "goto_prev_function"

# Move Lines Up/Down
"A-j" = "move_line_down"
"A-k" = "move_line_up"

[keys.insert]
ins = "normal_mode"
